### ISSUE TITLE
Compatibility with iOS 18

### ISSUE THREAD

**Issue by Cubik65536** [mchakravarty/ProjectNavigator#26]
Hi,

First of all, thanks for this project.

I'm also experimenting this with iOS 18, however I found out some problems while tinkering with iOS 18 simulator:

1. The file and directory changes are not saved. (This is not #27 because nothing was saved under iOS 18).
2. The toolbar/navigation bar are broken (the image shown below is the demo in this repo).

iOS 17:

![CleanShot 2024-08-05 at 22 47 29](https://github.com/user-attachments/assets/b370c886-469a-40b8-b508-039ea4dcd9e2)

iOS 18:

![CleanShot 2024-08-05 at 22 47 04](https://github.com/user-attachments/assets/788229b2-bedd-47dd-a9e0-fc90bcdfedc8)

Please do consider providing a fix or provide some work-around.

Best regards,

**Comment by mchakravarty** [comment]
Thanks for reporting this. I haven't tried using the iOS 18 beta so far, but given that we already had a few betas, I agree, it is time to give it a shot. I'll let you know what I find.

**Comment by Cubik65536** [comment]
> Thanks for reporting this. I haven't tried using the iOS 18 beta so far, but given that we already had a few betas, I agree, it is time to give it a shot. I'll let you know what I find.

@mchakravarty 

Thanks! I (sort of) solved the second UI issue by having my own toolbar setup, I will share it to you later when I've completed it.

I think for now #27 is the issue that should be taken care first because it seems that it influences the current stable OS (iPadOS 17). Please tell me if more information is needed.

**Comment by Cubik65536** [comment]
Some update on this.

I found no options for iOS 18 to hide the document toolbar (i.e.: the return button and the "rename" text field).

My workaround is to keep it while hiding all the toolbar of the `NavigationSplitView` and use another added button to control what's shown on the `NavigationSplitView`.

I will make a PR for this later.

**Comment by Cubik65536** [comment]
> Some update on this.
> 
> I found no options for iOS 18 to hide the document toolbar (i.e.: the return button and the "rename" text field).
> 
> My workaround is to keep it while hiding all the toolbar of the `NavigationSplitView` and use another added button to control what's shown on the `NavigationSplitView`.
> 
> I will make a PR for this later.

Another problem is that the name of the root directory in the navigator won't change if the project "file" is renamed via the Apple Document toolbar. One of the solutions I can think of is just not show the root directory as a folder and directly show all the sub-folders and files.

**Comment by mchakravarty** [comment]
Regarding the original issue (i.e., re the two screenshots on top). I simply added some dividers on iOS to be able to visually distinguish the different elements.  It's not pretty, but good enough for a demo app.
