### ISSUE TITLE
File modification are not saved if the file already have any content in it.

### ISSUE THREAD

**Issue by Cubik65536** [mchakravarty/ProjectNavigator#27]
Running OS: iPadOS 17.5.1 and 17.6

When the content of the file is modified, it is not saved, unless it is a newly created file with nothing in it. The behavior is shown in the video below (it is recorded with the simulator, but a real iPad behaves in the same way).

https://github.com/user-attachments/assets/b26f226b-39ee-4f76-b4d9-fd748dfe0f33

**Comment by Cubik65536** [comment]
P.S.: I don't know if this is somewhat related, but is there a way to manually update the navigator? (I don't know if this is the right term, but I mean write the current change and read from the saved file).

I came across the need of having to write some data directly to the package and save it as a file. If I write it directly, treating the package as a directory, the file won't show up in the Navigator until the next time the package is opened up, But, if I use `viewContext.add`, it is actually not written into the package until the file is closed and saved. But I do need to read it right after adding, and it has to be a file saved in the directory because of some tools I'm using....

/cc @mchakravarty

**Comment by Cubik65536** [comment]
This issue is resolved. I had to register undo with undoManager after the content of the file changed.

**Comment by mchakravarty** [comment]
Yes, you are right about the undo manager. Interestingly, this is only an issue on iOS. On macOS, the `TextEditor` does use the undo manager provided by the SwiftUI environment, but on iOS, `TextEditor` uses its own local one.

I fixes this in the demo app. Thanks for pointing it out.

**Comment by mchakravarty** [comment]
@Cubik65536 
> P.S.: I don't know if this is somewhat related, but is there a way to manually update the navigator? (I don't know if this is the right term, but I mean write the current change and read from the saved file).
> 
> I came across the need of having to write some data directly to the package and save it as a file. If I write it directly, treating the package as a directory, the file won't show up in the Navigator until the next time the package is opened up, But, if I use `viewContext.add`, it is actually not written into the package until the file is closed and saved. But I do need to read it right after adding, and it has to be a file saved in the directory because of some tools I'm using....

This is not directly related. The correct thing to do is to add the new file in memory (with `viewContext.add`. However, then you need to trigger a save operation of the document. Unfortunately, SwiftUI doesn't seem to provide that functionality.

In macOS, you can achieve it via grabbing the underlying `NSDocument` via AppKit, and then, triggering an autosave. Unfortunately, I haven't found a way to get at the underlying `UIDocument` on iOS. Do you know whether the `UIDocument` is somehow accessible via the `UIWindow` containing the SwiftUI views?

**Comment by Cubik65536** [comment]
> @Cubik65536
> 
> > P.S.: I don't know if this is somewhat related, but is there a way to manually update the navigator? (I don't know if this is the right term, but I mean write the current change and read from the saved file).
> > I came across the need of having to write some data directly to the package and save it as a file. If I write it directly, treating the package as a directory, the file won't show up in the Navigator until the next time the package is opened up, But, if I use `viewContext.add`, it is actually not written into the package until the file is closed and saved. But I do need to read it right after adding, and it has to be a file saved in the directory because of some tools I'm using....
> 
> This is not directly related. The correct thing to do is to add the new file in memory (with `viewContext.add`. However, then you need to trigger a save operation of the document. Unfortunately, SwiftUI doesn't seem to provide that functionality.
> 
> In macOS, you can achieve it via grabbing the underlying `NSDocument` via AppKit, and then, triggering an autosave. Unfortunately, I haven't found a way to get at the underlying `UIDocument` on iOS. Do you know whether the `UIDocument` is somehow accessible via the `UIWindow` containing the SwiftUI views?

Hi @mchakravarty 

I just came across your reply on X, I am currently using `viewContext.add` (by directly init a `Payload` with `Data`), but the problems where it's not saved troubles me a lot (that's why I started to consider if I can directly write to the document bundle).

I'm not aware of any way to get the `UIDocument`, but I will try to find something related to that.

Thanks for your response.

**Comment by Cubik65536** [comment]
I came across [this](https://stackoverflow.com/questions/68040086/filedocument-with-uimanageddocument-core-data), don't know if it's useful. It actually initializes its own `UIDocument` with the fileURL provided. /cc @mchakravarty

**Comment by mchakravarty** [comment]
I believe that `UIManagedDocument` is only relevant if you are using CoreData.

**Comment by mchakravarty** [comment]
I did experiment a bit and the `rootViewController` of the main window is a `UIDocumentBrowserViewController`. Usually, that should use a `UIDocumentViewController` for a subview, which in turn contains the `UIDocument` in its `document` property.
